apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-build
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gabbar/argocd-apps/build
    repoURL: 'git@github.com:ayeshasiddiqa161/test-apps-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true