# Name: stakater-nordmart-review.yaml (APP_NAME.yaml)
# Path: gabbar/argocd-apps/stage (TENANT_NAME/argocd-apps/ENV_NAME/)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-stage-stakater-nordmart-review
  namespace: openshift-gitops
spec:
  destination:
    namespace: gabbar-stage 
    server: 'https://kubernetes.default.svc'
  project: gabbar
  source:
    path: gabbar/stakater-nordmart-review/stage
    repoURL: 'git@github.com:ayeshasiddiqa161/test-apps-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
